### ISSUE TITLE
SDL not found (failed to init SDL thread priority manager)

### ISSUE THREAD

**Issue by d4rkd0s** [CyberAndrii/setup-steamcmd#1]
When using `CyberAndrii/setup-steamcmd@v1` to setup steamcmd, I'm getting this odd error when using **ubuntu-latest**

**Scanning content.....Warning: failed to init SDL thread priority manager: SDL not found**

```
Run steamcmd +login *** *** D26CV +run_app_build /home/runner/work/build/steam/app_build_000001.vdf +quit
Redirecting stderr to '/home/runner/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
Logging in user '***' to Steam Public ...
Logged in OK
Waiting for user info...OK
[2020-10-25 02:46:28]: Starting appID 000001 build (flags 0x0).
[2020-10-25 02:46:28]: Building depot 000001...


Building file mapping...
Scanning content.....Warning: failed to init SDL thread priority manager: SDL not found
..
Uploading content
[2020-10-25 02:46:49]: Successfully finished appID 000001build (BuildID 000001).
CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.
```

Unrelated, **CyberAndrii/steam-totp@v1** works great so thank you for making all these actions @CyberAndrii 👏

**Comment by d4rkd0s** [comment]
Found this similar GitHub issue https://github.com/ValveSoftware/steam-for-linux/issues/7036#issuecomment-636246155
where a user explains to install libsdl2 with:
`sudo apt install libsdl2-2.0-0:i386`

This is not a package found with ubuntu-latest, however the following packages can be installed:

`sudo apt install -y libsdl2-2.0-0 libsdl2-dev libsdl2-image-2.0-0 libsdl2-mixer-2.0-0 libsdl2-net-2.0-0 libsdl2-ttf-2.0-0`

Also found this, https://github.com/CM2Walki/steamcmd/pull/11/files

But this still doesn't help.

Any ideas?

**Comment by d4rkd0s** [comment]
Also found this, https://github.com/CM2Walki/steamcmd/pull/11/files

**Comment by astraxy** [comment]
same problem

**Comment by andriivitiv** [comment]
This warning does not cause any issues and can be ignored.

**Comment by d4rkd0s** [comment]
@CyberAndrii my upload still fails, as you can see in the original output I do see another error:
`CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 2 items discarded.`

When researching this I found the two following solutions:

https://www.reddit.com/r/Steam/comments/5xli69/excuse_me_steam_what_do_you_mean_by/

which asks to: 

> Delete ClientRegistry.blob from ~/Steam

and 

https://epochmod.com/forum/topic/42074-fixed-steamcmd-queue-not-empty/

which asks to:

> To Fix: Browse to your workshop directory (usually C:\steamcmd\steamapps\workshop) then delete everything from that folder.
> Run your steamcmd command again..

@CyberAndrii any ideas? Do you see this error when uploading builds?

**Comment by d4rkd0s** [comment]
Trying some things on my pipeline and will report back
cc: @Astraxy

**Comment by andriivitiv** [comment]
Added upload/download test in #2 but even with these errors everything works fine.
https://github.com/CyberAndrii/setup-steamcmd/runs/1325607318?check_suite_focus=true#step:11:56

Also in your log says that uploaded successfully so I think the problem is somewhere else.
> [2020-10-25 02:46:49]: Successfully finished appID 000001build (BuildID 000001).

What exit code do you get or any other error messages?

**Comment by d4rkd0s** [comment]
It was something on my end, thank you for showing me the upload/download test, that's awesome!

It was uploaded fine this morning when I ran the pipeline @CyberAndrii 😄 👍 
![image](https://user-images.githubusercontent.com/2348814/97812008-f55f9280-1c43-11eb-82fb-1f59be7e10d7.png)
